import type { Service } from "@/types/service.types";

/**
 * Contenido migrado del WordPress original (ver Fase 1, seccion "Servicios encontrados").
 * TODO: reemplazar textos placeholder por el contenido real extraido del HTTrack,
 * y las imagenes por los assets finales en /public/images/servicios/.
 */
export const services: Service[] = [
  {
    slug: "amarres-de-amor",
    title: "Amarres de amor",
    category: "amor",
    shortDescription:
      "Un trabajo espiritual dirigido a reconstruir el vinculo afectivo y atraer de vuelta el compromiso de esa persona.",
    longDescription:
      "TODO: contenido completo migrado desde la pagina original de amarres de amor.",
    priceNote: "Consulta de valoracion: gratuita",
    relatedSlugs: ["retorno-del-ser-amado", "endulzamientos"],
    process: [
      { order: 1, title: "Diagnostico energetico", description: "Se evalua la situacion actual del vinculo y las energias presentes." },
      { order: 2, title: "Ritual dirigido", description: "Se ejecuta el trabajo especifico para el caso, con seguimiento cercano." },
      { order: 3, title: "Acompanamiento", description: "Se guia al consultante durante el proceso de manifestacion del resultado." },
    ],
    benefits: ["Consulta inicial sin costo", "Seguimiento personalizado", "Confidencialidad total"],
    testimonials: [
      { id: "t1", quote: "Despues de meses sin hablar, volvio a buscarme.", authorInitials: "M.R.", relatedServiceSlug: "amarres-de-amor" },
    ],
    whatsappMessageTemplate: "Hola, quiero informacion sobre Amarres de amor",
    seo: {
      metaTitle: "Amarres de amor | El Brujo Llanero",
      metaDescription: "Trabajo espiritual serio para recuperar y fortalecer tu relacion. Consulta gratuita.",
      ogImage: "/images/servicios/amarres-de-amor.jpg",
      canonical: "/servicios/amarres-de-amor",
    },
  },
  {
    slug: "retorno-del-ser-amado",
    title: "Retorno del ser amado",
    category: "amor",
    shortDescription: "TODO: descripcion breve.",
    longDescription: "TODO: contenido completo.",
    priceNote: "Consulta de valoracion: gratuita",
    relatedSlugs: ["amarres-de-amor"],
    process: [],
    benefits: [],
    testimonials: [],
    whatsappMessageTemplate: "Hola, quiero informacion sobre Retorno del ser amado",
    seo: { metaTitle: "Retorno del ser amado | El Brujo Llanero", metaDescription: "TODO", ogImage: "/images/servicios/retorno-del-ser-amado.jpg", canonical: "/servicios/retorno-del-ser-amado" },
  },
  {
    slug: "endulzamientos",
    title: "Endulzamientos",
    category: "amor",
    shortDescription: "TODO: descripcion breve.",
    longDescription: "TODO: contenido completo.",
    priceNote: "Consulta de valoracion: gratuita",
    relatedSlugs: ["amarres-de-amor"],
    process: [], benefits: [], testimonials: [],
    whatsappMessageTemplate: "Hola, quiero informacion sobre Endulzamientos",
    seo: { metaTitle: "Endulzamientos | El Brujo Llanero", metaDescription: "TODO", ogImage: "/images/servicios/endulzamientos.jpg", canonical: "/servicios/endulzamientos" },
  },
  {
    slug: "amarre-de-dominio",
    title: "Amarre de dominio",
    category: "amor",
    shortDescription: "TODO: descripcion breve.",
    longDescription: "TODO: contenido completo.",
    priceNote: "Consulta de valoracion: gratuita",
    relatedSlugs: [],
    process: [], benefits: [], testimonials: [],
    whatsappMessageTemplate: "Hola, quiero informacion sobre Amarre de dominio",
    seo: { metaTitle: "Amarre de dominio | El Brujo Llanero", metaDescription: "TODO", ogImage: "/images/servicios/amarre-de-dominio.jpg", canonical: "/servicios/amarre-de-dominio" },
  },
  {
    slug: "embrujo-sexual",
    title: "Embrujo sexual",
    category: "amor",
    shortDescription: "TODO: descripcion breve.",
    longDescription: "TODO: contenido completo.",
    priceNote: "Consulta de valoracion: gratuita",
    relatedSlugs: [],
    process: [], benefits: [], testimonials: [],
    whatsappMessageTemplate: "Hola, quiero informacion sobre Embrujo sexual",
    seo: { metaTitle: "Embrujo sexual | El Brujo Llanero", metaDescription: "TODO", ogImage: "/images/servicios/embrujo-sexual.jpg", canonical: "/servicios/embrujo-sexual" },
  },
  {
    slug: "retiro-de-amantes",
    title: "Retiro de amantes",
    category: "amor",
    shortDescription: "TODO: descripcion breve.",
    longDescription: "TODO: contenido completo.",
    priceNote: "Consulta de valoracion: gratuita",
    relatedSlugs: ["corte-de-brujeria"],
    process: [], benefits: [], testimonials: [],
    whatsappMessageTemplate: "Hola, quiero informacion sobre Retiro de amantes",
    seo: { metaTitle: "Retiro de amantes | El Brujo Llanero", metaDescription: "TODO", ogImage: "/images/servicios/retiro-de-amantes.jpg", canonical: "/servicios/retiro-de-amantes" },
  },
  {
    slug: "limpias-espirituales",
    title: "Limpias espirituales",
    category: "proteccion",
    shortDescription: "TODO: descripcion breve.",
    longDescription: "TODO: contenido completo.",
    priceNote: "Consulta de valoracion: gratuita",
    relatedSlugs: ["proteccion-espiritual"],
    process: [], benefits: [], testimonials: [],
    whatsappMessageTemplate: "Hola, quiero informacion sobre Limpias espirituales",
    seo: { metaTitle: "Limpias espirituales | El Brujo Llanero", metaDescription: "TODO", ogImage: "/images/servicios/limpias-espirituales.jpg", canonical: "/servicios/limpias-espirituales" },
  },
  {
    slug: "corte-de-brujeria",
    title: "Corte de brujeria",
    category: "proteccion",
    shortDescription: "TODO: descripcion breve.",
    longDescription: "TODO: contenido completo.",
    priceNote: "Consulta de valoracion: gratuita",
    relatedSlugs: ["proteccion-espiritual", "limpias-espirituales"],
    process: [], benefits: [], testimonials: [],
    whatsappMessageTemplate: "Hola, quiero informacion sobre Corte de brujeria",
    seo: { metaTitle: "Corte de brujeria | El Brujo Llanero", metaDescription: "TODO", ogImage: "/images/servicios/corte-de-brujeria.jpg", canonical: "/servicios/corte-de-brujeria" },
  },
  {
    slug: "rituales",
    title: "Rituales",
    category: "consulta",
    shortDescription: "TODO: descripcion breve.",
    longDescription: "TODO: contenido completo.",
    priceNote: "Consulta de valoracion: gratuita",
    relatedSlugs: [],
    process: [], benefits: [], testimonials: [],
    whatsappMessageTemplate: "Hola, quiero informacion sobre Rituales",
    seo: { metaTitle: "Rituales | El Brujo Llanero", metaDescription: "TODO", ogImage: "/images/servicios/rituales.jpg", canonical: "/servicios/rituales" },
  },
  {
    slug: "proteccion-espiritual",
    title: "Proteccion espiritual",
    category: "proteccion",
    shortDescription: "TODO: descripcion breve.",
    longDescription: "TODO: contenido completo.",
    priceNote: "Consulta de valoracion: gratuita",
    relatedSlugs: ["corte-de-brujeria", "limpias-espirituales"],
    process: [], benefits: [], testimonials: [],
    whatsappMessageTemplate: "Hola, quiero informacion sobre Proteccion espiritual",
    seo: { metaTitle: "Proteccion espiritual | El Brujo Llanero", metaDescription: "TODO", ogImage: "/images/servicios/proteccion-espiritual.jpg", canonical: "/servicios/proteccion-espiritual" },
  },
  {
    slug: "consultas-espirituales",
    title: "Consultas espirituales",
    category: "consulta",
    shortDescription: "TODO: descripcion breve.",
    longDescription: "TODO: contenido completo.",
    priceNote: "Consulta de valoracion: gratuita",
    relatedSlugs: [],
    process: [], benefits: [], testimonials: [],
    whatsappMessageTemplate: "Hola, quiero informacion sobre Consultas espirituales",
    seo: { metaTitle: "Consultas espirituales | El Brujo Llanero", metaDescription: "TODO", ogImage: "/images/servicios/consultas-espirituales.jpg", canonical: "/servicios/consultas-espirituales" },
  },
];

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find((s) => s.slug === slug);
}

export const serviceSlugs = services.map((s) => s.slug) as [string, ...string[]];
